### PR TITLE
New Mobject: MultiPendulum and Pendulum

### PR DESCRIPTION
**Pull request by Iced-Tea3**
- Added MultiPendulum and Pendulum
- Adjusted `rigid_mechanics.py` to be compatible with opengl renderer
- adjusted `README.md`
- removed lint

### CODE REVIEW

**Comment by Matheart** [comment]
But is pendulum really necessary since pymunk could support that😂

**Comment by Iced-Tea3** [comment]
> But is pendulum really necessary since pymunk could support that😂

Haha, well, the main aim was to make it easy for people to use the pymunk features. 😅 This is a way to bridge that, i guess.

**Comment by Matheart** [comment]
Ah is pendulum also based on pymunk as well?

**Comment by Iced-Tea3** [comment]
Yup! i went through the tutorials and integrated it with rigid mechanics 😄

**Comment by Matheart** [comment]
Nice, btw the ElectricField still has some bugs to be fixed (check the project channel in discord, that blue arrow still exists when moving the object🥲

**Comment by Iced-Tea3** [comment]
> ElectricField still has some bugs to be fixed

Oh yeah, i saw that, i'll try and look into it

**Pull request merged**
